export default {
  NO_ROWS: parseInt(process.env.NO_ROWS, 10),
  NO_COLS: parseInt(process.env.NO_COLS, 10),
  START_LEVEL: parseInt(process.env.START_LEVEL, 10),
  DIRECTIONS: {
    N: 'N',
    S: 'S',
    E: 'E',
    W: 'W',
    NE: 'NE',
    NW: 'NW',
    SE: 'SE',
    SW: 'SW',
  },
  DIRECTIONS_STEP: {
    N: 3,
    S: 3,
    E: 3,
    W: 3,
    NE: 2,
    NW: 2,
    SE: 2,
    SW: 2,
  },
};
